# Generated by Django 4.0.2 on 2022-02-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='img',
            field=models.ImageField(default='aa.svg', null=True, upload_to=''),
        ),
    ]
