# Generated by Django 4.0.2 on 2022-02-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_title_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='img',
            field=models.ImageField(default='aa.jpg', null=True, upload_to=''),
        ),
    ]
